# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""Adapter Protocol — defines the contract for automation backends."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from fsq_mac.models import LocatorQuery


@runtime_checkable
class AutomationAdapter(Protocol):
    """Protocol that all automation backend adapters must satisfy."""

    # -- lifecycle ----------------------------------------------------------

    def connect(self, bundle_id: str | None = None) -> None: ...

    @property
    def connected(self) -> bool: ...

    def disconnect(self) -> None: ...

    # -- app operations -----------------------------------------------------

    def app_launch(self, bundle_id: str, arguments: list | None = None) -> dict: ...

    def app_activate(self, bundle_id: str) -> dict: ...

    def app_terminate(self, bundle_id: str) -> dict: ...

    def app_current(self) -> dict: ...

    def app_list(self) -> list[dict]: ...

    # -- element operations -------------------------------------------------

    def inspect(self, max_elements: int = 200) -> list[dict]: ...

    def find(self, value: str, strategy: str = "accessibility_id", timeout: int = 5) -> tuple[str, list[dict]]: ...

    def click(self, ref: str | LocatorQuery, strategy: str = "accessibility_id", timeout: int = 5) -> dict: ...

    def right_click(self, ref: str | LocatorQuery, strategy: str = "accessibility_id", timeout: int = 5) -> dict: ...

    def double_click(self, ref: str | LocatorQuery, strategy: str = "accessibility_id", timeout: int = 5) -> dict: ...

    def type_text(self, ref: str | LocatorQuery, text: str, strategy: str = "accessibility_id") -> dict: ...

    def scroll(self, ref: str | LocatorQuery, direction: str = "down", strategy: str = "accessibility_id") -> dict: ...

    def hover(self, ref: str | LocatorQuery, strategy: str = "accessibility_id", duration: float = 1.0) -> dict: ...

    def drag(self, source_ref: str | LocatorQuery, target_ref: str | LocatorQuery, strategy: str = "accessibility_id") -> dict: ...

    # -- input operations ---------------------------------------------------

    def input_key(self, key: str) -> dict: ...

    def input_hotkey(self, combo: str) -> dict: ...

    def input_text(self, text: str) -> dict: ...

    # -- capture ------------------------------------------------------------

    def screenshot(self, path: str) -> dict: ...

    def screenshot_element(self, ref: str, path: str, strategy: str = "accessibility_id") -> dict: ...

    def screenshot_rect(self, rect: str, path: str) -> dict: ...

    def ui_tree(self) -> str: ...

    # -- window -------------------------------------------------------------

    def window_current(self) -> dict: ...

    def window_list(self) -> list[dict]: ...

    def window_focus(self, index: int) -> dict: ...

    # -- wait ---------------------------------------------------------------

    def wait_element(self, value: str, strategy: str = "accessibility_id", timeout: int = 10) -> bool: ...

    def wait_window(self, title: str, timeout: float = 10) -> bool: ...

    def wait_app(self, bundle_id: str, timeout: float = 10) -> bool: ...

    # -- doctor helpers -----------------------------------------------------

    def check_server(self) -> tuple[bool, str]: ...

    # -- phase 2 interactions ----------------------------------------------

    def assert_visible(self, query: LocatorQuery) -> dict: ...

    def assert_enabled(self, query: LocatorQuery) -> dict: ...

    def assert_text(self, query: LocatorQuery, expected: str) -> dict: ...

    def assert_value(self, query: LocatorQuery, expected: str) -> dict: ...

    def menu_click(self, path: str) -> dict: ...

    def input_click_at(self, x: int, y: int) -> dict: ...
